/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author V.Prashoharan
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setSize (1140, 683);
        setResizable (false);
         // Center the JFrame on the screen
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Welcome to Little Flower Montessori");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, 40));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 517, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("“If teaching is to be effective with young children, it must assist them to advance on the way to independence. ”");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("  - Dr. Maria Montessori -");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 250, 72));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home (1).jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 640));

        jMenu3.setBackground(new java.awt.Color(153, 153, 153));
        jMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 6));
        jMenu3.setForeground(new java.awt.Color(255, 153, 0));
        jMenu3.setText("Home");
        jMenu3.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(153, 153, 153));
        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 6));
        jMenu4.setForeground(new java.awt.Color(255, 153, 0));
        jMenu4.setText("Students");
        jMenu4.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenu12.setBackground(new java.awt.Color(153, 153, 153));
        jMenu12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 4, true));
        jMenu12.setForeground(new java.awt.Color(255, 153, 0));
        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-student (1).png"))); // NOI18N
        jMenu12.setText("Add Student");
        jMenu12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenu12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenu12);

        jMenu13.setBackground(new java.awt.Color(153, 153, 153));
        jMenu13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 6, true));
        jMenu13.setForeground(new java.awt.Color(255, 153, 0));
        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Student-id-icon (1).png"))); // NOI18N
        jMenu13.setText("View Student");
        jMenu13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu13MouseClicked(evt);
            }
        });
        jMenu13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenu13);

        jMenuBar1.add(jMenu4);

        jMenu11.setBackground(new java.awt.Color(153, 153, 153));
        jMenu11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 6));
        jMenu11.setForeground(new java.awt.Color(255, 153, 0));
        jMenu11.setText("Books");
        jMenu11.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N

        jMenu5.setBackground(new java.awt.Color(153, 153, 153));
        jMenu5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 6, true));
        jMenu5.setForeground(new java.awt.Color(255, 153, 0));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bookdetails (1).png"))); // NOI18N
        jMenu5.setText("Book Details");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenu8.setBackground(new java.awt.Color(153, 153, 153));
        jMenu8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true));
        jMenu8.setForeground(new java.awt.Color(204, 204, 0));
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insertbook (1).png"))); // NOI18N
        jMenu8.setText(" Insert Books");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenu8);

        jMenu9.setBackground(new java.awt.Color(153, 153, 153));
        jMenu9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true));
        jMenu9.setForeground(new java.awt.Color(204, 204, 0));
        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/updatebook (1).png"))); // NOI18N
        jMenu9.setText(" Update Books");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenu9);

        jMenu10.setBackground(new java.awt.Color(153, 153, 153));
        jMenu10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true));
        jMenu10.setForeground(new java.awt.Color(204, 204, 0));
        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/deletebooks (1).png"))); // NOI18N
        jMenu10.setText(" Delete Books");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenu10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenu10);

        jMenu11.add(jMenu5);

        jMenuBar1.add(jMenu11);

        jMenu6.setBackground(new java.awt.Color(153, 153, 153));
        jMenu6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 6));
        jMenu6.setForeground(new java.awt.Color(255, 153, 0));
        jMenu6.setText("Calendar");
        jMenu6.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenu15.setBackground(new java.awt.Color(153, 153, 153));
        jMenu15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 6, true));
        jMenu15.setForeground(new java.awt.Color(255, 153, 0));
        jMenu15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/announcement (1).png"))); // NOI18N
        jMenu15.setText("Announcements");
        jMenu15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu15MouseClicked(evt);
            }
        });
        jMenu15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu15ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenu15);

        jMenuBar1.add(jMenu6);

        jMenu7.setBackground(new java.awt.Color(153, 153, 153));
        jMenu7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 6));
        jMenu7.setForeground(new java.awt.Color(255, 153, 0));
        jMenu7.setText("Events");
        jMenu7.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N

        jMenu16.setBackground(new java.awt.Color(153, 153, 153));
        jMenu16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 6, true));
        jMenu16.setForeground(new java.awt.Color(255, 153, 0));
        jMenu16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addevent (1).png"))); // NOI18N
        jMenu16.setText(" Add Event");
        jMenu16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu16MouseClicked(evt);
            }
        });
        jMenu16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu16ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenu16);

        jMenu17.setBackground(new java.awt.Color(153, 153, 153));
        jMenu17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 6, true));
        jMenu17.setForeground(new java.awt.Color(255, 153, 0));
        jMenu17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/view-event.png"))); // NOI18N
        jMenu17.setText(" View Event");
        jMenu17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu17MouseClicked(evt);
            }
        });
        jMenu17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu17ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenu17);

        jMenuBar1.add(jMenu7);

        jMenu14.setBackground(new java.awt.Color(153, 153, 153));
        jMenu14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 6));
        jMenu14.setForeground(new java.awt.Color(255, 153, 0));
        jMenu14.setText("About Us");
        jMenu14.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenu14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu14MouseClicked(evt);
            }
        });
        jMenu14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu14ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu14);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        new View.Form().setVisible(true); 
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
       new View.Form().setVisible(true); 
    }//GEN-LAST:event_jMenu12MouseClicked

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenu15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu15ActionPerformed
        new View.Calendar().setVisible(true); 
    }//GEN-LAST:event_jMenu15ActionPerformed

    private void jMenu15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu15MouseClicked
         new View.Calendar().setVisible(true);         
    }//GEN-LAST:event_jMenu15MouseClicked

    private void jMenu12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu12ActionPerformed

    private void jMenu13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu13ActionPerformed
          new View.Students().setVisible(true);        
    }//GEN-LAST:event_jMenu13ActionPerformed

    private void jMenu13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu13MouseClicked
          new View.Students().setVisible(true);        
    }//GEN-LAST:event_jMenu13MouseClicked

    private void jMenu14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu14ActionPerformed
          new View.AboutUs().setVisible(true);         
    }//GEN-LAST:event_jMenu14ActionPerformed

    private void jMenu14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu14MouseClicked
          new View.AboutUs().setVisible(true);         
    }//GEN-LAST:event_jMenu14MouseClicked

    private void jMenu16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu16ActionPerformed
        new View.Form2().setVisible(true); 
    }//GEN-LAST:event_jMenu16ActionPerformed

    private void jMenu16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu16MouseClicked
        new View.Form2().setVisible(true); 
    }//GEN-LAST:event_jMenu16MouseClicked

    private void jMenu17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu17ActionPerformed
       new View.Events().setVisible(true); 
    }//GEN-LAST:event_jMenu17ActionPerformed

    private void jMenu17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu17MouseClicked
        new View.Events().setVisible(true); 
    }//GEN-LAST:event_jMenu17MouseClicked

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
        new View.Books().setVisible(true);
    }//GEN-LAST:event_jMenu8ActionPerformed

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        new View.Books().setVisible(true);
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed
        new View.UpdateBooks().setVisible(true);
    }//GEN-LAST:event_jMenu9ActionPerformed

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        new View.UpdateBooks().setVisible(true);
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenu10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu10ActionPerformed
        new View.DeleteBooks().setVisible(true);
    }//GEN-LAST:event_jMenu10ActionPerformed

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        new View.DeleteBooks().setVisible(true);
    }//GEN-LAST:event_jMenu10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
